name: Deploy Python Flask App to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: shubham9319/python-flask:v1.0

    steps:

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SECRET_KEY }}
        service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Pull Docker image
      run: docker pull $DOCKER_IMAGE

    - name: Run Python Flask image on GCP VM
      run: |
        gcloud compute ssh minikube-vm --zone=us-central1-a --command="docker run -d -p 5000:5000 $DOCKER_IMAGE"

